import { FAQ, type ToolConfig } from "@/lib/site";

export function Steps() {
  const steps = [
    {
      n: 1,
      title: "Copy the link",
      text: "Open Instagram, tap the ⋯ or share icon on the post or reel and choose “Copy link”.",
    },
    {
      n: 2,
      title: "Paste it above",
      text: "Come back to QuickVideoSaver and paste the URL into the box, then press Download.",
    },
    {
      n: 3,
      title: "Save the file",
      text: "Pick the video, photo or audio you want and it downloads straight to your device.",
    },
  ];
  return (
    <section id="how-to" className="mx-auto max-w-4xl scroll-mt-20 px-4 py-14">
      <h2 className="text-center text-2xl font-extrabold tracking-tight text-slate-900 sm:text-3xl">How to download from Instagram</h2>
      <p className="mx-auto mt-2 max-w-xl text-center text-slate-500">Three quick steps — no app, no account, no watermark.</p>
      <ol className="mt-10 grid gap-6 sm:grid-cols-3">
        {steps.map((s) => (
          <li key={s.n} className="card relative p-6 pt-8 dark:border-slate-800 dark:bg-slate-900">
            <span className="ig-gradient absolute -top-4 left-6 inline-flex h-8 w-8 items-center justify-center rounded-full text-sm font-extrabold text-white shadow">
              {s.n}
            </span>
            <h3 className="text-lg font-bold text-slate-900 dark:text-slate-100">{s.title}</h3>
            <p className="mt-2 text-sm leading-relaxed text-slate-600 dark:text-slate-400">{s.text}</p>
          </li>
        ))}
      </ol>
    </section>
  );
}

export function Features({ tool }: { tool: ToolConfig }) {
  return (
    <section className="bg-slate-50 py-14 dark:bg-slate-950">
      <div className="mx-auto max-w-4xl px-4">
        <h2 className="text-center text-2xl font-extrabold tracking-tight text-slate-900 dark:text-slate-50 sm:text-3xl">Why use {tool.title}?</h2>
        <div className="mt-10 grid gap-5 sm:grid-cols-2">
          {tool.features.map((f) => (
            <div key={f.title} className="card flex gap-4 p-5 dark:border-slate-800 dark:bg-slate-900">
              <span className="mt-0.5 inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-brand-50 text-brand-600">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
                  <path d="M20 6 9 17l-5-5" />
                </svg>
              </span>
              <div>
                <h3 className="font-bold text-slate-900 dark:text-slate-100">{f.title}</h3>
                <p className="mt-1 text-sm leading-relaxed text-slate-600 dark:text-slate-400">{f.text}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

export function GuideContent({ tool }: { tool: ToolConfig }) {
  const guides: Record<ToolConfig["mode"], { title: string; paragraphs: string[]; tips: string[] }> = {
    video: {
      title: "How Instagram video downloads work",
      paragraphs: [
        "QuickVideoSaver is a browser tool for public Instagram media. It does not log into Instagram on your behalf. When you submit the original post or Reel URL, the service resolves the public information Instagram makes available and returns the media items that can be reached from that response.",
        "A useful distinction is the difference between the Instagram post URL and the long media CDN URL. The post URL identifies the public content; the CDN URL is a signed delivery address generated by Instagram and can expire. That is why the safest workflow is to keep the original Instagram URL and submit it again when an older download link stops working.",
        "The service does not re-encode the video to invent a higher resolution. The dimensions, codec and bitrate depend on the version Instagram exposes. A download can therefore be smaller or lower-resolution than the version you may have seen inside the Instagram app.",
        "Public availability can also change. A creator can delete a post, switch an account to private, or Instagram can change the data exposed to logged-out browsers. QuickVideoSaver cannot make inaccessible media public and does not attempt to bypass those restrictions.",
        "If you are downloading a video for anything beyond personal offline viewing, check the creator's permission first. Downloading a file does not transfer copyright or give you permission to republish, edit or commercially exploit it.",
      ],
      tips: ["Start with the original Instagram post or Reel URL.", "If a previous download link fails, submit the original URL again rather than editing a CDN URL.", "If Instagram itself cannot show the post publicly, the downloader cannot restore it.", "For commercial or public reuse, obtain permission from the rights holder."],
    },
    photo: {
      title: "How Instagram photo and carousel downloads work",
      paragraphs: [
        "Instagram photo posts can contain one image or several media items in a carousel. QuickVideoSaver reads the public post response and, when Instagram exposes the individual images, presents them separately so you can save the item you actually need.",
        "The original Instagram URL is important because image delivery URLs can be long, signed and temporary. Copying a CDN URL from one session and reusing it later can produce an error even when the post still exists. Re-submitting the public post gives the service a chance to resolve a current media URL.",
        "The downloaded file represents the image version Instagram makes available. The downloader does not manufacture missing detail or convert a small source into a genuinely higher-resolution original.",
        "A carousel can also contain videos. When mixed media is exposed, the result can include both image and video items. One unavailable item does not necessarily mean that every other item in the carousel is unavailable.",
        "Public access is not the same thing as copyright permission. If you plan to publish, redistribute or use an image commercially, obtain permission from the creator or rights holder.",
      ],
      tips: ["Use the public post URL rather than a copied CDN URL.", "For carousels, review the returned items individually.", "If an item is missing, refresh the original post and try again.", "Check the creator's reuse terms before publishing downloaded images."],
    },
    audio: {
      title: "How Instagram audio downloads work",
      paragraphs: [
        "QuickVideoSaver can expose the audio track from supported public videos and Reels. The extraction is performed in the browser after the public video is resolved, so the site does not need to upload the media to a separate audio-processing service.",
        "Audio availability depends on the source video. If Instagram does not provide an accessible public video, there is no reliable audio track for the downloader to extract. A Reel that requires login or has been removed therefore cannot be made downloadable by the tool.",
        "The resulting audio is derived from the source video. Extraction does not create a lossless copy of an original music file if the source video itself contains compressed audio.",
        "Music and other recorded sounds can have rights separate from the video. Saving audio for personal offline use is different from publishing it in another video, using it in advertising or redistributing it.",
      ],
      tips: ["Start with a public Reel or video URL.", "Confirm the original post plays without an Instagram login.", "Remember that audio can have separate copyright or licensing restrictions.", "Do not share your Instagram password with any downloader."],
    },
    reels: {
      title: "How Instagram Reel downloads work",
      paragraphs: [
        "A Reel URL points to an Instagram short-form video. QuickVideoSaver attempts to resolve the public media associated with that URL without asking for an Instagram login or session cookie.",
        "The public web representation of a Reel can change over time. Instagram may alter its response format, restrict access, or generate a new signed CDN address. For that reason, the original Reel URL is more useful than saving the final CDN address.",
        "When a Reel is publicly accessible, the service can return the video version Instagram exposes. It cannot bypass a private account, age or login gate, or deleted post, and it cannot recover a file that Instagram no longer makes available.",
        "Downloaded Reels remain the property of their creators or other rights holders. If you intend to repost a Reel, use it in a project or monetize it, obtain the necessary permission first.",
      ],
      tips: ["Open the Reel first to confirm it is publicly accessible.", "Re-submit the original Reel URL when an old link expires.", "Do not attempt to bypass private or login-only access.", "Check reuse permissions before publishing the downloaded video."],
    },
    stories: {
      title: "What to expect from Instagram story links",
      paragraphs: [
        "Stories are different from ordinary public posts because Instagram commonly places stronger access controls around them. QuickVideoSaver deliberately does not request Instagram credentials, so it cannot promise access to a story that Instagram only exposes to logged-in viewers.",
        "If a story is publicly reachable and Instagram exposes the required media information, the service can attempt to resolve it. If the story has expired, belongs to a private account or requires a login, there may be no public media URL for the service to use.",
        "The same distinction between a post URL and a temporary media URL applies here: use the original Instagram URL when retrying rather than copying a long CDN address.",
        "If the content is available as a normal public post or Reel, using that public post URL is generally more reliable than trying to process a story-specific link.",
      ],
      tips: ["Use a URL that opens publicly without an Instagram login.", "Never give your Instagram password to a downloader.", "Retry with the original post or Reel URL when available.", "Respect the creator's privacy and reuse permissions."],
    },
  };

  const guide = guides[tool.mode];

  return (
    <section className="mx-auto max-w-4xl px-4 py-14">
      <div className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900 sm:p-8">
        <h2 className="text-2xl font-extrabold tracking-tight text-slate-900 dark:text-slate-50 sm:text-3xl">{guide.title}</h2>
        <div className="mt-5 space-y-4 text-sm leading-7 text-slate-600 dark:text-slate-400">
          {guide.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}
        </div>
        <h3 className="mt-7 font-bold text-slate-900 dark:text-slate-100">Useful checks before downloading</h3>
        <ul className="mt-3 space-y-2 text-sm leading-6 text-slate-600 dark:text-slate-400">
          {guide.tips.map((tip) => <li key={tip} className="ml-5 list-disc">{tip}</li>)}
        </ul>
      </div>
    </section>
  );
}

export function Faq() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: FAQ.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };
  return (
    <section id="faq" className="mx-auto max-w-3xl scroll-mt-20 px-4 py-14">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <h2 className="text-center text-2xl font-extrabold tracking-tight text-slate-900 sm:text-3xl">Frequently asked questions</h2>
      <div className="mt-8 divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white">
        {FAQ.map((f, i) => (
          <details key={f.q} className="group px-5" open={i === 0}>
            <summary className="flex cursor-pointer items-center justify-between gap-4 py-4 text-left font-semibold text-slate-900">
              {f.q}
              <svg className="faq-chevron h-5 w-5 shrink-0 text-slate-400 transition" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
                <path d="m6 9 6 6 6-6" />
              </svg>
            </summary>
            <p className="pb-5 text-sm leading-relaxed text-slate-600">{f.a}</p>
          </details>
        ))}
      </div>
    </section>
  );
}
